// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://badaxvvshcezibpcjmhl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJhZGF4dnZzaGNlemlicGNqbWhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyOTYwMDMsImV4cCI6MjA2OTg3MjAwM30.Nfowd2fPM84uRLkRaQuMlFuLmfB6kyjCgGrzkXeVhMU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});